Type: AWS::S3::Bucket
Properties:
  AccessControl: Private
  LifecycleConfiguration:
    Rules:
      - ExpirationInDays: 90
        Id: Clean old build artifacts on whole bucket
        Status: Enabled
      - ExpirationInDays: 1
        Id: Clean cached build dependencies every 1 day
        Prefix: cache/archives/
        Status: Enabled